version: "3.5"

volumes:
  plutus-data:
  plutus1-data:
  plutus2-data:
  plutus3-data:
  plutus4-data:
  explorer-data:
  mn1:

services:
  n0:
    build: .
    command: [/app/entrypoint.sh]
    environment:
      REMOTES: '47.56.67.195:51472'
    ports:
      - "0.0.0.0:51473:51473"
      - "0.0.0.0:51472:51472"
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./plutus-data:/app/.plutus
    restart: always
